CREATE TABLE `advisors` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(200) NOT NULL,
	`name` varchar(200) NOT NULL,
	`title` varchar(300) NOT NULL DEFAULT '',
	`tagline` text,
	`heroImage` text,
	`badges` json DEFAULT ('[]'),
	`ctaPrimary` json,
	`ctaSecondary` json,
	`photoMain` text,
	`photoAccent` text,
	`meetEyebrow` varchar(100) DEFAULT '',
	`meetHeading` text,
	`bio` json DEFAULT ('[]'),
	`meetQuote` text,
	`stats` json DEFAULT ('[]'),
	`hotels` json DEFAULT ('[]'),
	`specialties` json DEFAULT ('[]'),
	`pillars` json DEFAULT ('[]'),
	`experiences` json DEFAULT ('[]'),
	`whyWorkBenefits` json DEFAULT ('[]'),
	`whyWorkImage` text,
	`testimonials` json DEFAULT ('[]'),
	`closingBannerImage` text,
	`closingBannerQuote` text,
	`email` varchar(320),
	`published` boolean NOT NULL DEFAULT false,
	`sortOrder` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `advisors_id` PRIMARY KEY(`id`),
	CONSTRAINT `advisors_slug_unique` UNIQUE(`slug`)
);
